wifi: Show and hide WIFI switch on-demand
ubports/indicator-network pull request #38
Opened 2020-07-10 10:01 UTC by fredldotme

Before these changes the WIFI switch hide/show state would only be evaluated at startup.
To support hotplugging WIFI adapters as well as late initialization like on the Pixel 3a,
we now make sure to hook into the hasWifiUpdated signal of the manager object to change the visibility on demand.

2020-07-23 09:29 UTC, fredldotme commented
This might need manual testing on a variety of devices I guess, so I wouldn't right out suggesting it to be included in OTA-13.
If you want me to change the PR to a draft though then let me know.

2020-10-01 18:50 UTC, fredldotme commented
Since this is now in the xenial_-_android9 branch I can either close this one or leave it open for testing on xenial devices before we merge over android9. What's preferred?

2020-10-01 20:05 UTC, Flohack74 commented
Idk whats the idea of the android9 branches as such, will tehy get stuff also down to 7.1 (xenial) branches? We can also cherry pick it, but this might be also working for older devices, and might bring a peace of mind for some devices where the wifi switch races on startup, and you need to reboot your device to get it back. This error was already reported a few times.

2020-10-02 18:09 UTC, dobey requested changes
Needs updated tests to go along with the change, and ensure that wifi switch visibility is updated appropriately under various conditions. Otherwise is looking OK though.

2020-11-13 11:23 UTC, Flohack74 commented
@fredldotme need help with the tests? ;)

2020-11-13 20:38 UTC, fredldotme commented
Probably not, just busy with a lot of debugging right now. Will try to look at them soon, if no one beats me to it.

2021-11-04 09:52 UTC, peat-psuwit commented
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your PR is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/merge_requests/38
However, you might not be able to push new code into it, as the branch resides in our repository. In case you need to update it, please open a new MR from your (new) fork. I don't have a better solution at the moment.

Sorry for your inconvenience.

2021-11-04 09:52 UTC, closed without merging